### ISSUE TITLE
Inductorless class-d amplifier in JAMMA cabinets

### ISSUE THREAD

**Issue by prrole** [tdaede/td-io#3]
Nice project, and good idea to use the RP2040.

Just a quick note to share some experience with this.  On a JAMMA project I experienced really bad video distortion/interference, when using it in a cabinet.  Long story short - I finally tracked it down to the inductorless class-d audio amplifier I used.  Internally in the cab, speaker and video signals were close on the JAMMA harness, like they usually are, and the PWM-like output of the audio amplifier interfered with the video signals.

**Comment by tdaede** [comment]
Indeed, inductorless is usually only usable with very short wires to the speaker. td-io uses LC filters for this reason.
