### ISSUE TITLE
About sync combiner?

### ISSUE THREAD

**Issue by herzmx** [tdaede/td-io#6]
First thanks for share this great proyect!

Noob question, it's possible send RGBS and RGBHV with sync combiner always active?

**Comment by tdaede** [comment]
The IO XNORs the syncs together (with pullups). This means that RGBS will be passed through (assuming V is disconnected or high) and RGBHV will be converted to RGBS (as long as it is active-low H and V)

**Comment by herzmx** [comment]
Thanks it's great have support to RGBS and RGBHV without switch!
