### ISSUE TITLE
Recommendation for F1-F6 voltage and current?

### ISSUE THREAD

**Issue by dangermousehouse** [tdaede/td-io#7]
Thank you for adding fuses to the most recent design! Do you have a recommendation for voltage/current on these fuses?

**Comment by tdaede** [comment]
The part is indicated in the Digikey field in the schematic: https://www.digikey.com/en/products/detail/bel-fuse-inc/0ZCG0050AF2C/4156100

Older versions use drivers with integrated current limiters, however those became unavailable.
